DarkPlasma_AutoHighlight:
  name: DarkPlasma_AutoHighlight
  year: 2018
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: '2021/10/29'
      version: '2.0.1'
      description: 'Torigoya_TextRuby.js でルビを振った際にエラーが発生する不具合を修正'
    - date: '2021/10/28'
      version: '2.0.0'
      description: 'rollup構成へ移行'
    - date: '2020/09/21'
      version: '1.3.2'
      description: '指定語句のうち、長いものを優先するよう修正'
    - description: 'スキル名と指定語句の判定衝突を修正'
    - date: '2020/04/14'
      version: '1.3.1'
      description: '指定したウィンドウが存在しない場合にエラーになる不具合を修正'
    - version: '1.3.0'
      description: '指定スキルの自動ハイライト機能追加'
    - version: '1.2.0'
      description: '自動ハイライトを有効にするウィンドウの設定を追加'
    - date: '2020/04/09'
      version: '1.1.0'
      description: 'Torigoya_TextRuby.jsに対応'
    - date: '2018/01/17'
      version: '1.0.1'
      description: '他の語句を含む語句がハイライトされない不具合の修正'
    - date: '2018/01/01'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '指定した語句に自動で色をつける'
  parameters:
    - param: highlightGroups
      text:
        ja: 色と語句
      desc:
        ja: ハイライトする際の色と語句を設定します。
      type: HighlightGroup[]
      default: []
    - param: targetWindows
      text:
        ja: 対象ウィンドウ
      desc:
        ja: 自動ハイライトの対象となるウィンドウクラスを指定します。
      type: string[]
      default:
        - Window_Message
  commands: []
  structures:
    HighlightGroup:
      - param: title
        text:
          ja: 名前
        desc:
          ja: 色と語句設定の名前を指定します。ご自身にとってわかりやすい名前をつけてください。
        type: string
      - param: color
        text:
          ja: 色
        desc:
          ja: 色番号を指定します。
        type: string
      - param: texts
        text:
          ja: 語句
        desc:
          ja: ハイライトしたい語句を指定します。
        type: string[]
        default: []
      - param: skills
        text:
          ja: スキル
        desc:
          ja: 名前をハイライトしたいスキルを指定します。
        type: skill[]
        default: []
      - param: items
        text:
          ja: アイテム
        desc:
          ja: 名前をハイライトしたいアイテムを指定します。
        type: item[]
        default: []
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      指定した語句を指定した色でハイライトします。
      Trb_TextColor.js などの適切なプラグインを使用することで、
      色番号にシャープ付きのカラーコードを指定できます。
