DarkPlasma_MapEventSkip:
  name: DarkPlasma_MapEventSkip
  year: 2023
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: 2023/02/05
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'イベントスキップ用プラグインコマンド'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      マップイベントをスキップするプラグインコマンドを提供します。

      skipEvent (ラベル名)
      ラベル名を省略するとイベントの最後まで飛びます。
