DarkPlasma_AllDeadState:
  name: DarkPlasma_AllDeadState
  year: 2023
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: 2023/04/18
      version: 1.0.1
      description: '不死身と組み合わせると敗北可を貫通する不具合を修正'
    - date: 2023/04/08
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '指定ステートで敗北判定させる'
  parameters:
    - param: states
      text:
        ja: ステート
      desc:
        ja: 指定ステートにかかったアクターは戦闘不能でなくとも敗北判定にカウントします。
      type: state[]
      default: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      アクターが指定したステートにかかっている場合、
      戦闘不能でなくとも敗北判定にカウントします。

      例えば、戦闘不能でないアクター全員が石化状態の場合
      敗北判定にできます。
