DarkPlasma_MemoriesSwitchLoader:
  name: DarkPlasma_MemoriesSwitchLoader
  year: 2021
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: 2021/12/29
      version: 1.0.1
      description: 'rollup構成へ移行'
    - date: 2021/05/05
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'シーン回想 CG閲覧のためのスイッチ読み込み'
  parameters: []
  commands: []
  structures:
  dependencies:
    base:
      - name: DarkPlasma_Memories
        version: 3.0.0
    orderAfter:
      - name: DarkPlasma_Memories
      - name: DarkPlasma_SharedSwitchVariable
    orderBefore: []
  help:
    ja: |
      DarkPlasma_Memories プラグインで利用するシーン回想 CG閲覧の
      解放条件スイッチのロードロジックを提供します
      DarkPlasma_SharedSwitchVariable プラグインで記録した
      共有セーブデータからロードします
