DarkPlasma_TextLog:
  name: DarkPlasma_TextLog
  year: 2017
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: 2023/11/23
      version: 3.0.0
      description: 'typescript移行'
    - description: 'YEP_MessageCore対応をオミット'
    - description: 'スワイプの挙動を逆方向に変更'
    - date: 2022/07/15
      version: 2.2.0
      description: 'メニュー禁止でもログを開けるように変更'
    - date: 2022/07/10
      version: 2.1.0
      description: '\XXX[YYY]のYYYをログから消す設定を追加'
    - date: 2021/11/26
      version: 2.0.0
      description: 'rollup構成へ移行'
    - description: '戦闘終了時に自動で区切り線を入れる設定を追加'
    - description: 'ログ開閉キーを複数設定できるように変更'
    - description: '不要な機能を削除'
    - date: 2021/07/07
      version: 1.12.0
      description: 'ログシーンの背景画像設定を追加'
    - description: 'ログウィンドウ枠非表示設定を追加'
    - date: 2021/07/05
      version: 1.11.0
      description: 'ログウィンドウの標準フォントサイズ設定を追加'
    - date: 2021/01/19
      version: 1.10.2
      description: 'EventReSpawn.js でイベントを削除した場合にエラーになる不具合を修正'
    - date: 2020/08/09
      version: 1.10.1
      description: 'NobleMushroom.js と併用した際に、場所移動後にウィンドウが表示され続ける不具合を修正'
    - date: 2020/08/07
      version: 1.10.0
      description: 'テキストログウィンドウ拡張用インターフェースを公開'
    - date: 2020/08/05
      version: 1.9.1
      description: 'MPP_ChoiceEx.js との競合を解消'
    - date: 2020/06/23
      version: 1.9.0
      description: 'プラグインコマンドでログを追加する機能を追加'
    - description: '外部向けログ追加インターフェース公開'
    - version: 1.8.3
      description: 'DarkPlasma_WordWrapForJapanese.js 等と併用しないとエラーになる不具合を修正'
    - date: 2020/06/03
      version: 1.8.2
      description: 'NobleMushroom.js と併用した際に、セーブ・ロード画面でログを開ける不具合を修正'
    - version: 1.8.1
      description: 'NobleMushroom.js と併用した際に、ポーズメニューでフリーズする不具合を修正'
    - description: 'タイトルに戻ってニューゲーム/ロードした際に、直前のデータのログを引き継ぐ不具合を修正'
    - date: 2020/05/30
      version: 1.8.0
      description: 'ログから戻った際に最後のメッセージを再表示しない設定を追加'
    - description: 'スクロールテキストをログに含める設定を追加'
    - description: '選択肢をログに含める設定を追加'
    - description: '高さ計算ロジックを整理'
    - date: 2020/05/09
      version: 1.7.3
      description: 'ログ表示/スクロール処理を軽量化'
    - version: 1.7.2
      description: 'ログ保存イベント数を超えるとログが壊れる不具合を修正'
    - date: 2020/05/08
      version: 1.7.1
      description: '軽微なリファクタ'
    - version: 1.7.0
      description: '名前ウィンドウの名前をログに含める設定を追加'
    - date: 2020/03/09
      version: 1.6.4
      description: 'プラグインが無効の状態で読み込まれていても有効と判定される不具合を修正'
    - date: 2020/01/28
      version: 1.6.3
      description: '文章を表示しないイベントに自動区切り線を入れないよう修正'
    - date: 2020/01/27
      version: 1.6.2
      description: '決定キーでログウィンドウを閉じられるよう修正'
    - description: 'ログ開閉キーにpagedownキーを設定できるよう修正'
    - version: 1.6.1
      description: 'ログ表示時の順序が逆になる不具合を修正'
    - description: 'DarkPlasma_WordWrapForJapanese（1.0.2以降）に対応'
    - version: 1.6.0
      description: 'ログウィンドウを開くボタンでログウィンドウを閉じられるよう修正'
    - description: 'メッセージ同士の間隔やテキストログの行間の設定項目を追加'
    - description: 'DarkPlasma_NameWindowに対応できていなかった不具合を修正'
    - description: '記録できるイベントログ数を無制限に変更'
    - description: '記録できるイベント数、メッセージ数の設定を追加'
    - description: 'イベントごとにログを区切る機能を追加'
    - date: 2020/01/23
      version: 1.5.3
      description: '選択肢が開いている最中にログウィンドウを開いて戻ろうとするとエラーで落ちる不具合を修正'
    - date: 2020/01/18
      version: 1.5.2
      description: 'DarkPlasma_NameWindowに対応'
    - date: 2017/10/07
      version: 1.5.1
      description: '冗長な変数名を修正'
    - description: 'パラメータの型を明示'
    - date: 2017/07/09
      version: 1.5.0
      description: 'マウスドラッグやスワイプでログウィンドウをスクロールする機能のおためし版を実装'
    - version: 1.4.0
      description: 'ログウィンドウがスクロール可能な場合にスクロール可能アイコンを表示する機能を実装'
    - version: 1.3.0
      description: 'ログが空の場合にメニューからログウィンドウを開こうとするとフリーズする不具合を修正'
    - description: '空のログウィンドウ表示可否フラグを実装'
    - date: 2017/07/08
      version: 1.2.1
      description: '選択肢でログに空文字列が記録される不具合を修正'
    - description: 'ログが空でもメニューやプラグインコマンドから開けた不具合を修正'
    - date: 2017/07/07
      version: 1.2.0
      description: 'プラグインコマンドからテキストログを開く機能を実装'
    - description: 'スイッチによるログ表示可能フラグON/OFF機能を実装'
    - version: 1.1.0
      description: 'スイッチによるログ記録のON/OFF機能を実装'
    - description: 'テキストログを開くボタンの変更機能を実装'
    - description: 'マウススクロールでもログのスクロールできる機能を実装'
    - description: 'マウス右クリックでもログを閉じることができる機能を実装'
    - description: 'マップ移動時にエラーで落ちる不具合を修正'
    - description: 'YEP_MainMenuManager.js に対応'
    - date: 2017/07/06
      version: 1.0.3
      description: '並列イベント終了時にログをリセットしないよう修正'
    - description: 'ブザーフラグが正しく動作していなかった不具合を修正'
    - version: 1.0.2
      description: 'バトルイベント終了時、コモンイベント終了時にログをリセットしないよう修正'
    - description: '長いイベントのログが正常にスクロールできていない不具合を修正'
    - version: 1.0.1
      description: 'デフォルトには存在しないメソッドを使用していた不具合を修正'
    - date: 2017/07/05
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'テキストログを保持・表示する'
  parameters:
    - param: maxVisibleMessages
      text:
        ja: 1画面のメッセージ数上限
      desc:
        ja: 1画面に表示する最大のメッセージ数を設定します。
      type: number
      default: 16
    - param: standardFontSize
      text:
        ja: 標準フォントサイズ
      desc:
        ja: ログウィンドウの標準フォントサイズを設定します。0でツクールのデフォルトを継承します。
      type: number
      default: 0
    - param: disableLoggingSwitch
      text:
        ja: ログ記録無効スイッチ
      desc:
        ja: 設定したスイッチがONの間はログを残しません。0の場合、常にログを残します。
      type: switch
      default: 0
    - param: openLogKeys
      text:
        ja: ログ開閉ボタン
      desc:
        ja: テキストログウィンドウを開閉するためのボタンを設定します。
      type: select[]
      default: [pageup]
      options:
        - name: pageup
        - name: pagedown
        - name: shift
        - name: control
        - name: tab
    - param: disableLogWindowSwitch
      text:
        ja: ログウィンドウ無効スイッチ
      desc:
        ja: 設定したスイッチがONの間はログウィンドウを開けません。0の場合、常に開けます。
      type: switch
      default: 0
    - param: showLogWindowWithoutText
      text:
        ja: 白紙ログでも開く
      desc:
        ja: ONの場合、ログに表示すべきテキストがない場合でもログウィンドウを開けます。
      type: boolean
      default: true
    - param: lineSpacing
      text:
        ja: ログの行間
      desc:
        ja: ログの行間を設定します。
      type: number
      default: 0
    - param: messageSpacing
      text:
        ja: メッセージ間隔
      desc:
        ja: ログのメッセージの間隔を設定します。メッセージはイベントコマンド単位でひとかたまりです。
      type: number
      default: 0
    - param: logSplitter
      text:
        ja: ログ区切り線
      desc:
        ja: イベントの切れ目などに挟むための区切り線を設定します。
      type: string
      default: '-------------------------------------------------------'
    - param: autoSplit
      text:
        ja: 自動区切り線
      desc:
        ja: ONの場合、バトル、コモン、並列イベントを除くイベント終了時に区切り線を自動で入れます。
      type: boolean
      default: true
    - param: autoSplitWhenBattleEnd
      text:
        ja: 戦闘終了時区切り線
      desc:
        ja: ONの場合、戦闘終了時に区切り線を自動で入れます。
      type: boolean
      default: true
    - param: includeName
      text:
        ja: 名前をログに含む
      desc:
        ja: ONの場合、名前ウィンドウの名前をログに含めます。
      type: boolean
      default: true
    - param: includeScrollText
      text:
        ja: スクロールテキストをログに含む
      desc:
        ja: ONの場合、スクロールテキストをログに含めます。
      type: boolean
      default: false
    - param: includeChoice
      text:
        ja: 選んだ選択肢をログに含む
      desc:
        ja: ONの場合、選んだ選択肢をログに含めます。
      type: boolean
      default: true
    - param: choiceFormat
      text:
        ja: 選択肢フォーマット
      desc:
        ja: ログに表示する選択肢のフォーマットを設定します。{choice}は選んだ選択肢に変換されます。
      type: string
      default: 選択肢:{choice}
    - param: choiceColor
      text:
        ja: 選択肢色
      desc:
        ja: ログに表示する選択肢の色を設定します。
      type: number
      default: 17
    - param: includeChoiceCancel
      text:
        ja: キャンセルをログに含む
      desc:
        ja: ONの場合、選択肢をキャンセルしたことをログに含めます。選んだ選択肢をログに含むがONの場合のみ有効です。
      type: boolean
      default: true
    - param: choiceCancelText
      text:
        ja: キャンセルログ
      desc:
        ja: 選択肢をキャンセルした際に記録する内容を設定します。
      type: string
      default: キャンセル
    - param: smoothBackFromLog
      text:
        ja: テキスト再表示なし
      desc:
        ja: ONの場合、ログシーンから戻った際にテキストを再度表示し直しません。
      type: boolean
      default: true
    - param: backgroundImage
      text:
        ja: 背景画像
      desc:
        ja: ログシーンに表示する背景画像を設定します。
      type: file
      dir: img
    - param: showLogWindowFrame
      text:
        ja: ウィンドウ枠表示
      desc:
        ja: ONの場合、ログウィンドウ枠を表示します。
      type: boolean
      default: true
    - param: escapeCharacterCodes
      text:
        ja: パラメータを除外したい制御文字
      desc:
        ja: \XXX[YYY]の形式でYYYをログから消したい場合、ここにXXXを追加します。
      type: string[]
      default: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      イベントのテキストログを表示します。

      イベント会話中またはマップ上で pageup キー（L2ボタン）でログを表示します。
      イベント会話中はそのイベントの直前までのログを表示します。
      ログは上下キーでスクロールすることができます。
      キャンセルキーやログ開閉キーでログから抜け、イベントやマップに戻ります。

      注意: テキスト再表示なしをONにしている場合、
      Scene_Map.prototype.createMessageWindow 及び
      Scene_Map.prototype.createScrollTextWindow の処理を上書きします。
      これらの関数に処理を加えているプラグインとは競合する恐れがありますので、
      それらよりも下にこのプラグインを追加してください。
      この設定がOFFになっている場合、
      イベントに戻る際、最後のメッセージをもう一度最初から流します。

      メニュー拡張系のプラグインでは、
      下記スクリプトからログを開くことができます。
       this.commandTextLog.bind(this)

      プラグインコマンド showTextLog から開くことも可能です。

      プラグインコマンド insertLogSplitter を使用することで、
      イベントログに区切り線を追加できます。
      自動イベント区切り線 設定をONにしておくことで、
      イベントごとに自動で区切り線を挿入させることもできます。

      プラグインコマンド insertTextLog XXXX を使用することで、
      イベントログに任意のログを追加できます。

      操作方法（デフォルト）
       pageupキー（L2ボタン） : ログを表示する
       上下キー/マウススクロール : ログをスクロールする
       キャンセルキー/右クリック : ログから抜ける

      マウスドラッグやスワイプでもログをスクロールできますが、
      環境差異に関して未検証なのでおためし版です。
      しばらく使われて問題が報告されなければ正式版とします。

      外部向けインターフェース
       $gameSystem.insertTextLog(text): ログに文字列 text を追加します。

      拡張プラグインを書くことで、テキストログウィンドウにおける
      エスケープ文字の複雑な挙動を定義できます。
      詳細は DarkPlasma_TextLogExtensionExample.js を参照してください。
