DarkPlasma_OrderIdAlias:
  name: DarkPlasma_OrderIdAlias
  year: 2021
  license: MIT
  histories:
    - date: '2021/08/31'
      version: '2.0.0'
      description: 'rollup構成へ移行'
    - description: 'MOT_ItemFavoriteSort.js との互換性を削除'
    - date: '2020/05/25'
      version: '1.0.3'
      description: '装備欄のソート順が壊れる不具合を修正'
    - date: '2019/10/29'
      version: '1.0.2'
      description: '装備を外すとエラーになる不具合の修正'
    - date: '2019/08/20'
      version: '1.0.1'
      description: 'MOT_ItemFavoriteSort.js がない時にエラーになる不具合の修正'
    - version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'スキル/アイテムの表示順序IDを書き換える'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      アイテムまたはスキルの順序がID順の場合、メモ欄に以下のように記述することで、
      IDの代わりにその数値を順序として使います。
      <orderId:xxx> xxxは整数値
