DarkPlasma_SkillDetail:
  name: DarkPlasma_SkillDetail
  year: 2021
  license: MIT
  histories:
    - date: '2021/09/20'
      version: '2.0.0'
      description: '一部のキーを指定すると詳細を表示できない不具合を修正'
    - description: 'パラメータを整理'
    - description: 'rollup構成へ移行'
    - date: '2020/04/15'
      version: '1.3.0'
      description: '詳細説明テキストのスクロールに対応'
    - date: '2020/04/14'
      version: '1.2.0'
      description: '説明表示中にカーソル移動の有効無効を切り替える設定を追加'
    - version: '1.1.1'
      description: '戦闘中にスキル画面でフリーズする不具合を修正'
    - date: '2020/04/13'
      version: '1.1.0'
      description: 'Window_SkillDetail を他プラグインから拡張できるように修正'
    - version: '1.0.1'
      description: '詳細説明ウィンドウを表示しながら決定/キャンセルを押した際にウィンドウを閉じるように修正'
    - version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'スキルに詳細説明文を追加する'
  parameters:
    - param: openDetailKey
      text:
        ja: 詳細説明ボタン
      desc:
        ja: 詳細説明を開くためのボタン
      type: select
      options:
        - name: pageup
        - name: pagedown
        - name: shift
        - name: control
        - name: tab
      default: shift
    - param: detailWindowRect
      text:
        ja: 座標とサイズ
      desc:
        ja: 詳細説明ウィンドウの座標とサイズ
      type: WindowRect
      default:
        x: 0
        y: 288
        width: 816
        height: 336
  commands: []
  structures:
    WindowRect:
      - param: x
        text:
          ja: X座標
        type: number
        default: 0
      - param: y
        text:
          ja: Y座標
        type: number
        default: 288
      - param: width
        text:
          ja: 横幅
        type: number
        default: 816
      - param: height
        text:
          ja: 高さ
        type: number
        default: 336
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      スキル画面のスキルにカーソルを合わせて特定のボタンを押すと
      スキル詳細説明画面を開きます。

      スキルのメモ欄に下記のような記述で詳細説明を記述できます。
      <Detail:詳細説明文。
      ～～～～。>
