DarkPlasma_SkillCooldown:
  name: DarkPlasma_SkillCooldown
  year: 2020
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: '2021/11/14'
      version: '2.0.0'
      description: 'rollup構成へ移行'
    - date: '2021/11/12'
      version: '1.2.1'
      description: '戦闘中にパーティメンバーを変更するとエラーが発生する不具合を修正'
    - date: '2021/03/01'
      version: '1.2.0'
      description: 'クールタイムに変数を利用する機能を追加'
    - date: '2020/05/07'
      version: '1.1.0'
      description: 'クールタイムがセーブデータに含まれる不具合を修正'
    - description: '控えメンバーのクールタイムに関する設定を追加'
    - date: '2020/04/24'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'スキルにクールタイムを指定する'
  parameters:
    - param: skillCooldowns
      text:
        ja: スキルクールタイム
      type: SkillCooldown[]
      default: []
    - param: displayCooldown
      text:
        ja: クールタイム表示
      desc:
        ja: ONの場合、スキル消費の代わりにクールタイムを表示します。
      type: boolean
      default: true
    - param: cooldownFormat
      text:
        ja: クールタイム表示形式
      desc:
        ja: スキルクールタイムの表示形式を設定します。{turn}がターン数に置き換えられます。
      type: string
      default: CT:{turn}
    - param: cooldownColor
      text:
        ja: クールタイム色
      desc:
        ja: スキルクールタイムの表示色を設定します。
      type: number
      default: 2
    - param: decreaseBenchwarmersCooldown
      text:
        ja: 控えクールタイム減
      desc:
        ja: ONの場合、控えメンバーのクールタイムも進めます。
      type: boolean
      default: true
  commands: []
  structures:
    SkillCooldown:
      - param: triggerSkillId
        text:
          ja: トリガースキル
        desc:
          ja: クールタイムを発生させるトリガーとなるスキルを設定します。
        type: skill
      - param: targets
        text:
          ja: 対象
        desc:
          ja: クールタイムを発生させる対象を設定します。
        type: SkillCooldownTarget[]
        default: []
    SkillCooldownTarget:
      - param: skillId
        text:
          ja: スキル
        desc:
          ja: クールタイムを発生させる対象となるスキルを指定します。
        type: skill
      - param: turnCount
        text:
          ja: ターン数(定数)
        desc:
          ja: クールタイムのターン数を定数で設定します。
        type: number
        default: 3
      - param: turnCountVariable
        text:
          ja: ターン数(変数)
        desc:
          ja: クールタイムのターン数を変数で設定します。定数で指定した値に対して、変数の値を加算します。
        type: variable
        default: 0
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      スキルにクールタイムを指定します。
      スキルX使用後、スキルYの使用を一定ターン数制限することができます。
