DarkPlasma_MessageWindowInMenu:
  name: DarkPlasma_MessageWindowInMenu
  year: 2021
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: '2021/11/03'
      version: '1.0.0'
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'メニューにメッセージウィンドウを追加する'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      メニュー画面でメッセージウィンドウを表示できるようにします。
