DarkPlasma_MaskPicture:
  name: DarkPlasma_MaskPicture
  year: 2024
  license: MIT
  excludeLicenseManager: false
  histories:
    - date: 2024/04/04
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'ピクチャをマスクする'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      ピクチャでピクチャをマスクするプラグインコマンドを提供します。
      
      MaskPicture 1 2
      ピクチャ1をピクチャ2でマスクします。

      UnmaskPicture 1
      ピクチャ1にかけたマスクを解除します。
